sudo: required
language: generic

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker'
  env: 'docker-env-1'
  bucket_name: 'elasticbeanstalk-us-west-2-998626419377'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
